version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ssuminn/test:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
